#!/bin/bash

FULLPATH=$(realpath $0)
SCRIPTPATH=$(dirname $FULLPATH)
# Activate virtualenv if exist
source $SCRIPTPATH/venv/bin/activate 2>/dev/null

# Run script
python3 $SCRIPTPATH/cookiedoor.py $@
